FEATURE: Only output existing images and allow upscaling
sitegeist/Sitegeist.Kaleidoscope pull request #70
Opened 2023-09-27 09:37 UTC by manuelmeister

This is a draft pr to limit srcset output to only existing images. 

I'm not sure I feel comfortable merging it like this. Maybe we first need a PR to add tests, so we can ensure that everything  still works correctly.

Fixes #33

2023-10-13 09:43 UTC, mficzel commented
I like the idea, more precisely i think the biggest generated image should be the largest possible image with the required aspect ratio if there is an aspect ratio defined, otherwise the original one.

2023-10-26 12:49 UTC, manuelmeister commented
That's exactly what I've done.

I've also increased the minimum php version to 7.4 as it [did not support an extended return type](https://github.com/sitegeist/Sitegeist.Kaleidoscope/actions/runs/6653945993/job/18080982197#step:5:28).

2023-10-27 13:02 UTC, mficzel commented
@manuelmeister thanks a lot for the pr. Need to find some time and mindset for a proper review as this is non trivial.

2024-01-29 21:12 UTC, manuelmeister commented
@mficzel Can you have a look again?

2024-06-01 12:28 UTC, mficzel commented
I do not like the allowUpscaling argument that is passed around all over the place and adds quite a bit of complexity while i think that upscaling general is not a good idea. Also this pr does some unrelated things that look valuable but should not be mixed in this one.

How about this approach:
1. Add a method. `supportsUpscaling(): bool` to the scalableImageSourceInterface
2. Asset Image source should return `false` while DummyImageSource should return `true` 
3. Skip srcset items that would yield a bigger image if the CurrentImageSource does not supportsUpscaling 

That way we have strong defaults and anyone that has a need for upscaling images can still create a custom AssetImageSource

2024-06-01 12:39 UTC, mficzel commented
@manuelmeister i talked with @bweinzierl at the contribution day and he is willing to help here aswell. 

BTW: A thing that is important to me is that the pr only does what is mentioned. The cleanups you added are nice but make reviewing harder. It would be great to split those topics into separate prs.

2024-06-03 15:52 UTC, manuelmeister commented
@mficzel I agree with your comments. I'm not sure how to continue with the preserve aspect ratio.

2024-06-20 15:25 UTC, manuelmeister commented
@mficzel I removed the aspect ratio part from this PR and opened a new one:  #77

2024-07-01 13:09 UTC, mficzel requested changes
I like this now. However do we really have to add the "supportUpscaling" flag? I see no real user case for that and would leave this out and always assume allowUpscalinj = false. Just to make the tests for us a little bit easier.

2024-07-01 13:09 UTC, mficzel commented on Classes/Domain/AbstractImageSource.php
Theroretically breaky if one implemented the scalableImageSourceInterface without using the AbstractScalableImageSource as a base ... i do not think this is a real case

2024-07-01 16:50 UTC, manuelmeister commented on Classes/Domain/AbstractImageSource.php
I don't understand

2024-07-01 17:25 UTC, mficzel commented on Classes/Domain/AbstractImageSource.php
Not that important. I meant I consider this theoretical and not a real problem. So this is fine.

2024-08-19 11:52 UTC, manuelmeister commented
For a project we needed the image upscaling, to ensure the images are the same.

2024-08-29 15:14 UTC, mficzel reviewed
I generally approve. This makes sense and i am fine with the structure. Will do some extra testing before merging to be extra sure this is as non breaky as possible,

Thanks for the pr.

2024-09-27 10:11 UTC, mficzel approved these changes

2024-09-27 10:22 UTC, merged